[project]
name = "translation-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deep-translator>=1.11.4",
    "mss>=10.1.0",
    "pytesseract>=0.3.13",
]
