[project]
name = "translation-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deep-translator>=1.11.4",
    "opencv-python>=4.12.0.88",
    "pytesseract>=0.3.13",
    "textblob>=0.19.0",
]
